### PR TITLE
Fixes #81 replacing $timeout by $interval

### LINKED ISSUE #81: Replace $timeout by $interval to allow tests with protractor
Protractor wait for $timeout to finish before start testing. Growl ttl should use $interval instead, to enable protractor to validate the notification message. 

https://github.com/marcorinck/angular-growl/issues/43
angular/protractor#169

### PR DESCRIPTION
**Pull request by gastonelhordoy**
...and making notifications being testable by protractor

### CODE REVIEW

**Comment by gastonelhordoy** [comment]
I ran the tests in karma, tried it out manually and also executed my E2E protractor tests. Everything looks good. This will really help in making protractor tests faster by not waiting for notifications to be closed.

**Comment by flippinjoe21** [comment]
Would you mind adding your karma tests to the project?

**Comment by mikey0000** [comment]
+1 $timeout breaks protractor tests

**Comment by mikey0000** [comment]
What can I do to get this merged? This is a bit of a blocker for our project E2E tests.

**Comment by flippinjoe21** [comment]
From above 


"Would you mind adding your karma tests to the project?"


This still applies

**Comment by mikey0000** [comment]
@flippinjoe21 If its what it takes I'll submit a pull request with tests myself.

**Comment by Swilvan** [comment]
What I'm wondering about is that this shouldn't change any functionality right? So why wouldn't the normal tests succeeding be good enough?

**Comment by gastonelhordoy** [comment]
Sorry @flippinjoe21 for the delay in replying. So yes, I think @Swilvan is right, I didn't add any new feature, so existing test cases should be enough. How could I cover this change in any way that has not yet been covered by existing karma tests?

**Comment by flippinjoe21** [comment]
@gastonelhordoy All I'm asking is that you add in the tests that you created.   Mostly because of the lack of testing that is currently being done.    I'm not asking you to add tests to verify your change.   Simply add in your tests so that they will be available going forward.

Also at this point you need to merge your copy with the latest since there have been some changes made causing conflicts.

**Comment by Swilvan** [comment]
So I created a PR with this fix without any merge issues, would be nice to have this update since it really speeds up protractor if you use these notifications a bit.

**Comment by flippinjoe21** [comment]
Closed in favor of https://github.com/JanStevens/angular-growl-2/pull/103

**Pull request closed without merging**
