### PR TITLE
feat: Return the configuration object on config methods.

### LINKED ISSUE #72: Feature request: Return the configuration object on config methods
Right now I'm setting the global configuration as this:

      growlProvider.globalTimeToLive(5000);
      growlProvider.globalDisableIcons(true);

which reads awfully.

When doing:

      growlProvider
                .globalTimeToLive(5000)
                .globalDisableIcons(true);

It is triggering the following error:

    growlProvider.globalTimeToLive(...) is undefined

so it appears it is not retuning the `growlProvider` instance.

Can this be added so we can chain config setters?

### PR DESCRIPTION
**Pull request by diosney**
Fixes #72.

### CODE REVIEW

**Comment by m00s** [comment]
+1

**Comment by diosney** [comment]
Any updates on this?

**Comment by flippinjoe21** [comment]
Please merge master into your branch.   Also please don't run the build.

**Comment by diosney** [comment]
@flippinjoe21 Done!

**Pull request merged**
